name: rick_and_morty_api
description: Rick And Morty API
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  http: ^0.13.0
  json_annotation: ^4.0.0

dev_dependencies:
  test: ^1.17.5
  very_good_analysis: ^2.1.1
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  mocktail: ^0.1.4
